# Project
version=1.2.0+1.19.2
group=com.putzwirk
java_version=17

# Common
minecraft_version=1.19.2
common_runs_enabled=false
common_client_run_name=Common Client
common_server_run_name=Common Server

# Mod options
mod_name=Artifacts Merging
mod_author=neuromuser
mod_id=artifactsmerging
license=MIT
credits=
description=Combine items into a random one from configurable merge lists.
minecraft_version_range=[1.19.2,1.20)

# Fabric
fabric_version=0.77.0+1.19.2
fabric_loader_version=0.14.9

# Forge
forge_version=43.5.2
forge_loader_version_range=[43,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.java.home=/usr/lib/jvm/java-17-openjdk
org.gradle.daemon=false
