version=1.2.0
group=com.putzwirk
java_version=17

minecraft_version=1.20.4
mod_name=Artifacts Merging
mod_author=neuromuser
mod_id=artifactsmerging
license=MIT
credits=
description=Combine items into a random one from configurable merge lists.
minecraft_version_range=[1.20.4, 1.21)

fabric_version=0.92.1+1.20.4
fabric_loader_version=0.15.3
modmenu_version=9.2.0

forge_version=49.0.19
forge_loader_version_range=[49,)
forge_version_range=[49,)

org.gradle.jvmargs=-Xmx3G
org.gradle.java.home=/usr/lib/jvm/java-17-openjdk
org.gradle.daemon=false
