# Project
version=1.2.0
group=com.putzwirk
java_version=17

# Common
minecraft_version=1.20.1
mod_name=Artifacts Merging
mod_author=neuromuser
mod_id=artifactsmerging
license=MIT
credits=
description=Combine items into a random one from configurable merge lists.
minecraft_version_range=[1.20.1, 1.22)
parchment_minecraft=1.20.1
parchment_version=2023.09.03

# Fabric
fabric_version=0.92.1+1.20.1
fabric_loader_version=0.16.9

# Forge
forge_version=47.2.30
forge_loader_version_range=[47,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.java.home=/usr/lib/jvm/java-17-openjdk
org.gradle.daemon=false
